import { LEGAL } from "../config";
import type { LegalDocument } from "../types";

const C = LEGAL;

export const termsOfService: LegalDocument = {
  slug: "terms",
  title: "Terms of Service",
  summary: "Rules governing access to and use of the Vigilant platform.",
  lastUpdated: C.effectiveDate,
  sections: [
    {
      heading: "1. Agreement",
      paragraphs: [
        `These Terms of Service ("Terms") are a binding agreement between you and ${C.companyLegalName} ("${C.productDisplayName}," "we," "us," or "our") for access to the ${C.productName} platform, including our website, progressive web application, APIs, and mobile applications (collectively, the "Service").`,
        `By creating an account, accessing the Service, or clicking to accept these Terms, you agree to be bound by them. If you use the Service on behalf of an organization, you represent that you have authority to bind that organization, and "you" refers to that organization.`,
        `If you do not agree to these Terms, do not use the Service.`,
      ],
    },
    {
      heading: "2. The Service",
      paragraphs: [
        `${C.productDisplayName} provides agentic target-intelligence monitoring. The Service discovers, indexes, and analyzes publicly available information about companies, people, tickers, and other targets you configure ("Targets"), and may generate summaries, signals, briefs, and alerts using automated systems including large language models.`,
        `The Service is intended for lawful business intelligence, competitive research, investment research, and similar professional use. It is not legal, financial, investment, or compliance advice.`,
      ],
    },
    {
      heading: "3. Accounts and eligibility",
      paragraphs: [
        `You must be at least 18 years old and capable of forming a binding contract to use the Service. You are responsible for maintaining the confidentiality of your account credentials and for all activity under your account.`,
        `You agree to provide accurate registration information and to keep it current. Notify us promptly at ${C.securityEmail} if you suspect unauthorized access to your account.`,
      ],
    },
    {
      heading: "4. Subscriptions, billing, and usage limits",
      paragraphs: [
        `Certain features may require a paid subscription. Fees, billing cycles, and plan limits will be presented at checkout or in an order form. Unless otherwise stated, subscriptions renew automatically until canceled.`,
        `You authorize us and our payment processors to charge applicable fees and taxes. Usage-based charges (including API, agent run, and LLM consumption costs) may apply according to your plan or configured budget caps.`,
        `We may change pricing upon reasonable notice. Price changes apply to subsequent billing periods unless otherwise required by law.`,
      ],
    },
    {
      heading: "5. Acceptable use",
      paragraphs: [
        `Your use of the Service is subject to our Acceptable Use Policy, incorporated by reference. You may not use the Service to violate law, infringe rights, scrape or access data in violation of site terms, harass individuals, conduct unauthorized surveillance, or interfere with the Service.`,
      ],
    },
    {
      heading: "6. Customer data and monitoring configuration",
      paragraphs: [
        `You retain ownership of information you submit to the Service, including Target definitions, notes, and configuration ("Customer Data"). You grant us a limited license to host, process, transmit, and display Customer Data solely to provide, secure, and improve the Service.`,
        `You represent that you have all rights and lawful basis necessary to configure monitoring of each Target and that your use complies with applicable law, including privacy, employment, securities, and anti-stalking laws.`,
      ],
    },
    {
      heading: "7. Public and third-party information",
      paragraphs: [
        `The Service may retrieve and process information from publicly accessible sources and third-party services. We do not guarantee completeness, accuracy, timeliness, or continued availability of any source or output.`,
        `Third-party sites and services are governed by their own terms. You are responsible for ensuring your use of retrieved information complies with applicable restrictions, including robots.txt, terms of use, and copyright law.`,
      ],
    },
    {
      heading: "8. AI-generated outputs",
      paragraphs: [
        `Summaries, briefs, signals, and other outputs may be generated by automated systems and may contain errors, omissions, or hallucinations. Outputs are provided for informational purposes only and must not be relied upon as the sole basis for decisions.`,
        `See our Intelligence & AI Disclaimer for additional limitations.`,
      ],
    },
    {
      heading: "9. Intellectual property",
      paragraphs: [
        `We and our licensors own the Service, software, branding, documentation, and all related intellectual property, excluding Customer Data. Subject to these Terms and your plan, we grant you a limited, non-exclusive, non-transferable, revocable license to access and use the Service for your internal business purposes.`,
        `You may not reverse engineer, copy, resell, or create derivative works of the Service except as permitted by law or our open-source notices.`,
      ],
    },
    {
      heading: "10. Confidentiality and beta features",
      paragraphs: [
        `Non-public information about the Service, including unreleased features, pricing, and security details, is our confidential information. Beta or preview features are provided "as is," may change without notice, and may be subject to additional terms.`,
      ],
    },
    {
      heading: "11. Privacy",
      paragraphs: [
        `Our Privacy Policy describes how we collect and use personal information. By using the Service, you acknowledge our privacy practices.`,
      ],
    },
    {
      heading: "12. Suspension and termination",
      paragraphs: [
        `We may suspend or terminate access if you breach these Terms, create security risk, fail to pay fees, or if required by law. You may cancel at any time through account settings or by contacting ${C.supportEmail}.`,
        `Upon termination, your right to use the Service ends. We may delete Customer Data after a reasonable retention period unless law requires longer storage. Sections that by nature should survive termination will survive.`,
      ],
    },
    {
      heading: "13. Disclaimers",
      paragraphs: [
        `THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE." TO THE MAXIMUM EXTENT PERMITTED BY LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, NON-INFRINGEMENT, AND ACCURACY OF OUTPUTS.`,
      ],
    },
    {
      heading: "14. Limitation of liability",
      paragraphs: [
        `TO THE MAXIMUM EXTENT PERMITTED BY LAW, NEITHER WE NOR OUR SUPPLIERS WILL BE LIABLE FOR INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR FOR LOST PROFITS, REVENUE, DATA, OR GOODWILL.`,
        `OUR TOTAL LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATED TO THE SERVICE IN ANY 12-MONTH PERIOD WILL NOT EXCEED THE GREATER OF (A) AMOUNTS YOU PAID US FOR THE SERVICE IN THAT PERIOD OR (B) ONE HUNDRED U.S. DOLLARS (US$100), EXCEPT WHERE LIABILITY CANNOT BE LIMITED BY LAW.`,
      ],
    },
    {
      heading: "15. Indemnification",
      paragraphs: [
        `You will defend, indemnify, and hold harmless ${C.productDisplayName} and its officers, directors, employees, and agents from claims arising out of your Customer Data, your Targets, your use of the Service, or your violation of these Terms or applicable law.`,
      ],
    },
    {
      heading: "16. Dispute resolution",
      paragraphs: [
        `These Terms are governed by the laws of ${C.governingLaw}, without regard to conflict-of-law rules. Except where prohibited, exclusive jurisdiction and venue for disputes will be the state or federal courts located in ${C.governingLawShort}.`,
        `Either party may seek injunctive relief for misuse of intellectual property or confidential information.`,
      ],
    },
    {
      heading: "17. Changes",
      paragraphs: [
        `We may modify these Terms by posting an updated version and updating the "Last updated" date. Material changes will be notified by email or in-product notice where required. Continued use after the effective date constitutes acceptance.`,
      ],
    },
    {
      heading: "18. Contact",
      paragraphs: [
        `Questions about these Terms: ${C.legalEmail}`,
        `${C.companyLegalName}`,
        C.registeredAddress,
      ],
    },
  ],
};
