export const LAUNCH = {
  brand: "VIGILANTE",
  offer: {
    badge: "3 AI AGENTS · $10/MO",
    promo: "Code VIGILANTE → 50% off ($5/mo)",
    edge: "Three specialized AI agents on every competitor — your edge over manual research.",
  },
  hero: {
    headline: "3 AI agents run your competitor analysis.",
    subhead:
      "$10/mo for three AI agents that discover pages, diff changes, and write the brief. Use code VIGILANTE for 50% off — $5/mo for full coverage.",
  },
  differentiators: [
    {
      title: "3 AI AGENTS",
      body: "One discovers sources, one diffs changes, one writes the brief — parallel competitor analysis no spreadsheet can match.",
    },
    {
      title: "REAL PAGES",
      body: "Snapshots pricing, IR, and careers — not news headlines about a change.",
    },
    {
      title: "AUTO DIFFS",
      body: "Hashed baselines on day one. Real changes surface on your schedule.",
    },
    {
      title: "SOURCED BRIEFS",
      body: "Intel from indexed pages and SEC filings. Every claim links back.",
    },
  ],
  steps: [
    {
      num: "01",
      title: "DISCOVER",
      body: "Agent 1 maps pricing, IR, careers, and filings for any company.",
      accent: "#6E9BE6",
    },
    {
      num: "02",
      title: "INDEX",
      body: "Agent 2 snapshots every page and pulls SEC filings for public companies.",
      accent: "#A78BFA",
    },
    {
      num: "03",
      title: "DIFF",
      body: "Agent 3 hashes baselines and surfaces pricing and hiring shifts first.",
      accent: "#E3B341",
    },
    {
      num: "04",
      title: "BRIEF",
      body: "All three agents deliver a daily brief — valuations, actions, what to watch.",
      accent: "#4ADE80",
    },
  ],
  sections: {
    howTitle: "Three agents. One pass.",
    whyTitle: "Your edge: AI agents, not interns.",
    pricingTitle: "3 AI agents for $10/mo.",
    pricingSub:
      "The plan built for competitor analysis. Nothing charged on the waitlist — billing starts when your workspace opens.",
    accountsTitle: "Your workspace. Your watches.",
    accountsBody: "Magic link in. Each team runs isolated watchlists and briefs.",
    ctaTitle: "Get 3 AI agents on your waitlist.",
    ctaBody: "Join now — $10/mo at launch, or $5/mo with code VIGILANTE. We email when your workspace is ready.",
    demoHint: "Type any company above. Full app at",
  },
  pricing: [
    {
      id: "growth",
      name: "GROWTH",
      price: "$10",
      period: "/mo",
      agents: "3 AI agents",
      detail: "Full competitor analysis — discover, diff, brief",
      highlight: true,
    },
    {
      id: "free",
      name: "FREE",
      price: "$0",
      period: "",
      agents: "2 agents",
      detail: "Daily diffs, briefs, SEC EDGAR",
      highlight: false,
    },
    {
      id: "team",
      name: "TEAM",
      price: "$20",
      period: "/mo",
      agents: "6+ agents",
      detail: "Higher scan limits, priority support",
      highlight: false,
    },
    {
      id: "custom",
      name: "CUSTOM",
      price: "Let's talk",
      period: "",
      agents: "Enterprise",
      detail: "SSO, custom sources, SLA",
      highlight: false,
      custom: true,
    },
  ],
  personas: [
    {
      id: "sarah",
      name: "Sarah Chen",
      org: "Stripe",
      role: "Competitive PM",
      email: "sarah@stripe.com",
      watches: ["GOOGLE", "MICROSOFT", "ADYEN"],
      highlight: "Google Cloud pricing — 3 tiers restructured",
    },
    {
      id: "james",
      name: "James Okonkwo",
      org: "a16z",
      role: "Investor",
      email: "james@a16z.com",
      watches: ["OPENAI", "ANTHROPIC", "STRIPE"],
      highlight: "SEC 8-K — material partnership filed",
    },
    {
      id: "maya",
      name: "Maya Patel",
      org: "Figma",
      role: "Corp Dev",
      email: "maya@figma.com",
      watches: ["ADOBE", "CANVA", "MIRO"],
      highlight: "12 enterprise AE roles posted in 48h",
    },
  ],
  marquee: {
    rowA: [
      "3 AI AGENTS",
      "$10/MO",
      "VIGILANTE 50% OFF",
      "COMPETITOR ANALYSIS",
      "PRICING PAGES",
      "SEC EDGAR",
      "CAREERS",
      "DAILY BRIEFS",
    ],
    rowB: [
      "AUTO DIFFS",
      "SOURCE LINKS",
      "10-K · 10-Q · 8-K",
      "HIRING SIGNALS",
      "3 AGENTS · $5 W/ PROMO",
      "WATCHLISTS",
      "SLACK ALERTS",
      "MULTI-TENANT",
    ],
  },
};
