export const LAUNCH = {
  brand: "VIGILANTE",
  offer: {
    badge: "3 AI AGENTS · $10/MO",
    promo: "VIGILANTE → 50% off first month",
    edge: "Source-level competitor intel — not news alerts.",
  },
  hero: {
    headline: "Know what competitors changed before your team does.",
    subhead:
      "Three AI agents watch pricing pages, filings, and careers sites — then diff changes and write sourced briefs. Growth plan: $10/mo. Code VIGILANTE cuts it to $5.",
  },
  differentiators: [
    {
      title: "THREE AGENTS",
      body: "Discovery, diffing, and briefing run in parallel — full coverage without spreadsheet archaeology.",
    },
    {
      title: "PRIMARY SOURCES",
      body: "Snapshots competitor-owned pages. You see the change at the source, not a blog post about it.",
    },
    {
      title: "REAL DIFFS",
      body: "Content hashing on day one. Pricing, packaging, and hiring shifts surface on your cadence.",
    },
    {
      title: "LINKED BRIEFS",
      body: "Every insight cites a URL or filing. Share with product, sales, or investors with confidence.",
    },
  ],
  steps: [
    {
      num: "01",
      title: "DISCOVER",
      body: "Agent 1 maps pricing, investor relations, careers, and SEC filings for any company.",
      accent: "#6E9BE6",
      hint: "Try it in the demo above ↑",
    },
    {
      num: "02",
      title: "INDEX",
      body: "Agent 2 snapshots every page and ingests EDGAR for public peers.",
      accent: "#A78BFA",
      hint: "Overview tab after discovery",
    },
    {
      num: "03",
      title: "DIFF",
      body: "Agent 3 compares baselines and flags material moves — pricing first, then hiring velocity.",
      accent: "#E3B341",
      hint: "Insights & changes feed",
    },
    {
      num: "04",
      title: "BRIEF",
      body: "All three agents produce a daily brief: what changed, why it matters, what to do next.",
      accent: "#4ADE80",
      hint: "Brief tab in product demo",
    },
  ],
  sections: {
    howTitle: "Four steps. Zero manual scraping.",
    whyTitle: "Built for teams that need proof, not rumors.",
    pricingTitle: "Simple plans. Serious coverage.",
    pricingSub:
      "Join the waitlist free — billing starts when your workspace opens. Founding members get $10/mo credit × 6 months.",
    accountsTitle: "One workspace per team.",
    accountsBody: "Magic-link sign-in. Isolated watchlists, briefs, and alerts per account.",
    ctaTitle: "Reserve your spot.",
    ctaBody: "Early access is waitlist-only. We'll email when your workspace is ready — no charge today.",
    demoHint: "Live discovery below · Full workspace at",
  },
  pricing: [
    {
      id: "growth",
      name: "GROWTH",
      price: "$10",
      period: "/mo",
      agents: "3 AI agents",
      detail: "Full competitor analysis — discover, diff, brief",
      highlight: true,
    },
    {
      id: "free",
      name: "FREE",
      price: "$0",
      period: "",
      agents: "2 agents",
      detail: "Daily diffs, briefs, SEC EDGAR",
      highlight: false,
    },
    {
      id: "team",
      name: "TEAM",
      price: "$20",
      period: "/mo",
      agents: "6+ agents",
      detail: "Higher scan limits, priority support",
      highlight: false,
    },
    {
      id: "custom",
      name: "CUSTOM",
      price: "Let's talk",
      period: "",
      agents: "Enterprise",
      detail: "SSO, custom sources, SLA",
      highlight: false,
      custom: true,
    },
  ],
  personas: [
    {
      id: "pm",
      name: "Alex R.",
      org: "Series B SaaS",
      role: "Competitive PM",
      email: "alex@company.com",
      watches: ["ACME", "RIVALCO", "NORTHSTAR"],
      highlight: "Rival packaging page — Enterprise tier removed",
    },
    {
      id: "investor",
      name: "Jordan M.",
      org: "Growth fund",
      role: "Investor",
      email: "jordan@fund.com",
      watches: ["PORTCO A", "PORTCO B", "SECTOR LEAD"],
      highlight: "8-K filed — strategic partnership disclosed",
    },
    {
      id: "corpdev",
      name: "Sam K.",
      org: "Product company",
      role: "Corp Dev",
      email: "sam@product.co",
      watches: ["TARGET A", "TARGET B", "ADJACENT"],
      highlight: "14 sales roles posted in 72 hours",
    },
  ],
  marquee: {
    rowA: [
      "PRICING PAGES",
      "SEC EDGAR",
      "CAREERS SIGNALS",
      "PAGE DIFFS",
      "DAILY BRIEFS",
      "SOURCE LINKS",
      "WATCHLISTS",
      "SLACK ALERTS",
    ],
    rowB: [
      "COMPETITIVE INTEL",
      "10-K · 10-Q · 8-K",
      "INVESTOR RELATIONS",
      "PACKAGING CHANGES",
      "HIRING VELOCITY",
      "MULTI-TENANT",
      "AI AGENTS",
      "PRIMARY SOURCES",
    ],
  },
};
