import type { Analysis, Brief, Signal } from "@/types/database";

export const MOCK_ANALYSES: Analysis[] = [
  {
    id: "demo-1",
    user_id: "demo-user",
    name: "Acme Corp — Pricing",
    target_type: "company",
    target: "Acme Corp",
    sources: ["https://example.com/pricing"],
    cadence_minutes: 1440,
    model: "claude-sonnet",
    budget_cap_usd: 10,
    spend_usd: 2.847,
    status: "live",
    last_run_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    next_run_at: new Date(Date.now() + 22 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-2",
    user_id: "demo-user",
    name: "Jane Doe — LinkedIn",
    target_type: "person",
    target: "Jane Doe",
    sources: ["https://example.com/profile"],
    cadence_minutes: 360,
    model: "claude-sonnet",
    budget_cap_usd: 5,
    spend_usd: 4.92,
    status: "live",
    last_run_at: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    next_run_at: new Date(Date.now() + 5.5 * 60 * 60 * 1000).toISOString(),
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "demo-3",
    user_id: "demo-user",
    name: "NVDA ticker watch",
    target_type: "ticker",
    target: "NVDA",
    sources: ["https://example.com/quote/nvda"],
    cadence_minutes: 60,
    model: "claude-sonnet",
    budget_cap_usd: 15,
    spend_usd: 0.124,
    status: "paused",
    last_run_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    next_run_at: null,
    created_at: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_SIGNALS: Signal[] = [
  {
    id: "sig-1",
    analysis_id: "demo-1",
    type: "pricing",
    title: "Pro tier price increased 12%",
    detail: "Acme raised Pro from $49/mo to $55/mo on their public pricing page.",
    severity: "high",
    source_url: "https://example.com/pricing",
    created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
  },
  {
    id: "sig-2",
    analysis_id: "demo-1",
    type: "promo",
    title: "New annual discount banner",
    detail: "Homepage now promotes 20% off annual plans through end of quarter.",
    severity: "med",
    source_url: "https://example.com/pricing",
    created_at: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sig-3",
    analysis_id: "demo-2",
    type: "person",
    title: "New VP Product role listed",
    detail: "Profile headline updated to VP Product at Horizon Labs.",
    severity: "med",
    source_url: "https://example.com/profile",
    created_at: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sig-4",
    analysis_id: "demo-1",
    type: "hiring",
    title: "3 new sales openings posted",
    detail: "Careers page added AE roles in EMEA — possible expansion signal.",
    severity: "low",
    source_url: "https://example.com/careers",
    created_at: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sig-5",
    analysis_id: "demo-2",
    type: "site",
    title: "Bio section rewritten",
    detail: "About section now emphasizes AI infrastructure experience.",
    severity: "low",
    source_url: "https://example.com/profile",
    created_at: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sig-6",
    analysis_id: "demo-1",
    type: "newsletter",
    title: "Acme newsletter: Pro tier launch",
    detail: "Product digest announces new Pro tier and enterprise positioning.",
    severity: "med",
    source_url: "https://example.com/newsletter",
    created_at: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sig-7",
    analysis_id: "demo-1",
    type: "patent",
    title: "US20240123456 published",
    detail: "ML inference patent assigned to Acme subsidiary.",
    severity: "low",
    source_url: "https://example.com/patent",
    created_at: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "sig-8",
    analysis_id: "demo-2",
    type: "insider",
    title: "SVP Engineering hire signal",
    detail: "LinkedIn activity suggests leadership change at target company.",
    severity: "high",
    source_url: "https://example.com/profile",
    created_at: new Date(Date.now() - 12 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_BRIEF: Brief = {
  id: "brief-1",
  analysis_id: "demo-1",
  title: "Acme moves upmarket on pricing",
  body: "Acme raised Pro pricing 12% and launched an annual discount push, signaling confidence and a hunt for higher-ACV customers. Combined with new EMEA sales hires, they may be preparing a regional expansion play worth monitoring closely.",
  created_at: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
};

export const MOCK_ANALYSIS_MAP = new Map(
  MOCK_ANALYSES.map((a) => [a.id, a.name])
);
